config/routes.rb
Rails.application.routes.draw do
  get 'champion/list'

  get 'equipment/list'

  get 'game_object/show'

  root 'index#show'
end

app/views/index/_game_objects.html.erb
<% @game_objects.each do | g_obj | %>
  <tr class="item">
    <td>
      <%= link_to image_tag( g_obj.file_name ), game_object_show_path( id: g_obj.id ),
        {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'} %>
      <div> <%= g_obj.name %> </div>
    </td>
  </tr>
<% end %>

app/views/index/show.html.erb
<%= form_tag( {:controller => 'index', :action => 'show'}, :method => 'get', :id => 'search_form', :class => 'well right', :remote => true ) do %>
  <div class="form-group">
    <label for="card_name:">Card name:
      <%= text_field_tag( 'card_name', @card_name || '', { :autocomplete => :off, :size => 75 } ) %>
    </label>
    <label for="set_selector">Set:
      <%= select_tag( 'set_selector[]', options_for_select( @sets.map { | h | h[ :name ] }, @set_selector ),
                    { :multiple => "multiple", :id => 'set_selector', :autocomplete => :off } ) %>
    </label>
    <label for="type_selector">Type:
      <%= select_tag( 'type_selector[]', options_for_select( @types.map { | h | h[ :name ] }, @type_selector ),
                    { :multiple => "multiple", :id => 'type_selector', :autocomplete => :off } ) %>
    </label>
    <label for="sub_type_selector">Subtype:
      <%= select_tag( 'sub_type_selector[]', options_for_select( @sub_types.map { | h | h[ :name ] }, @sub_type_selector ),
                    { :multiple => "multiple", :id => 'sub_type_selector', :autocomplete => :off } ) %>
    </label>
    <label for="cost_selector">Cost:
      <%= select_tag( 'cost_selector[]', options_for_select( @costs.map { | h | h[ :name ] }, @cost_selector ),
                    { :multiple => "multiple", :id => 'cost_selector', :autocomplete => :off } ) %>
    </label>
    <label for="shard_selector">Shard:
    <%= select_tag( 'shard_selector[]', options_for_select( @shards.map { | h | [ h[ :name ], { 'data-img' => h[ :data_img ] } ] }, @shard_selector ),
                    { :multiple => "multiple", :id => 'shard_selector', :autocomplete => :off } ) %>
    </label>
    <label for="selected_shards_only_selector">Selected shards only:
      <%= check_box_tag( 'sel_shards_only_selector', @sel_shards_only_selector ? '2' : '1', @sel_shards_only_selector || false,
                         { :id => 'sel_shards_only_selector', :autocomplete => :off } ) %>
    </label>
    <label for="rarity_selector">Rarity:
      <%= select_tag( 'rarity_selector[]', options_for_select( @rarities.map { | h | h[ :name ] }, @rarity_selector ),
                    { :multiple => "multiple", :id => 'rarity_selector', :autocomplete => :off } ) %>
    </label>
    <label for="pvp_only_selector">PVP cards only:
      <%= check_box_tag( 'pvp_only_selector', @pvp_only_selector ? '2' : '1', @pvp_only_selector || false,
                      { :id => 'pvp_only_selector', :autocomplete => :off } ) %>
    </label>
  </div>
<% end %>
<div class="well right">
  <div class="infinite-table">
    <table>
      <%= render :partial => 'game_objects', :object => @game_objects %>
    </table>
    <p class="pagination">
      <%= link_to_next_page( @game_objects, 'Next Page', :remote => true, :params => { :scroll => true } ) %>
    </p>
  </div>
</div>
<%= javascript_include_tag( 'multiselect_loader.js' ) %>

app/views/index/show.js.erb
<% if @scroll %>
// Append new data
$( "<%=j render( :partial => 'game_objects', :object => @game_objects ) %>" )
    .appendTo( $( ".infinite-table table" ) );
<% else %>
// Replace table
$( ".infinite-table table" ).html("<%=j render( :partial => 'game_objects', :object => @game_objects ) %>" );
<% end %>

// Update pagination link
<% if @game_objects.last_page? %>
$( '.pagination' ).html( "That's all for now!" );
<% else %>
$( '.pagination' )
    .html( "<%=j link_to_next_page( @game_objects, 'Next Page', :remote => true, :params => {
    :scroll => true,
    :set_selector => @set_selector,
    :card_name => @card_name,
    :type_selector => @type_selector,
    :cost_selector => @cost_selector,
    :sub_type_selector => @sub_type_selector,
    :shard_selector => @shard_selector,
    :rarity_selector => @rarity_selector,
    :pvp_only_selector => @pvp_only_selector,
    :sel_shards_only_selector => @sel_shards_only_selector
    } ) %>" );
<% end %>